name: server
description: A server app using the shelf package and Docker.
version: 1.0.0
# homepage: https://www.example.com
publish_to: "none"

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  drpc:
    path: "../drpc"

  args: ^2.0.0
  shelf: ^1.1.0
  shelf_router: ^1.0.0
  freezed_annotation: ^2.1.0
  json_annotation: ^4.7.0
  shelf_cors_headers: ^0.1.4
  lorem_gen: ^2.0.1
  path: ^1.8.2
  http: ^0.13.0
  hive: ^2.2.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.15.0
